src/main/java/com/iozee/printadmin/view/UserMB.java
package com.iozee.printadmin.view;

import org.springframework.security.core.context.SecurityContextHolder;
import com.iozee.printadmin.security.SecurityUtils;
import com.iozee.printadmin.utils.ViewUtils;
import com.iozee.printadmin.model.User;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.io.IOException;
import java.io.Serializable;
import java.util.Map;

@ManagedBean
@ViewScoped
public class UserMB implements Serializable {

    private String username;

    private String password;

    private static final int idleTimeout = 1000 * 60 * 30; // 30 min

    private final int countdown = 120;  // 120 sec

    public User getCurrentUser() {
        return SecurityUtils.getCurrentUser();
    }

    public int getIdleTimeout() {
        return idleTimeout;
    }

    public int getCountdown() {
        return countdown;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void logout() {
        SecurityContextHolder.clearContext();
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect("login");
        } catch (IOException e) {
            ViewUtils.showError();
        }
    }

    public void onIdle() {
        String script = "PF('idleTimerKnob').setValue(" + countdown + ");" +
                "PF('idleTimerDialog').show();" +
                "PF('idleTimer').start();";
        ViewUtils.executeJavaScript(script);
    }

    public void onActive() {
        String script = "PF('idleTimerKnob').setValue(" + countdown + ");" +
                "PF('idleTimerDialog').hide();" +
                "PF('idleTimer').stop(true);";
        ViewUtils.executeJavaScript(script);
    }

    public String getErrorCode() {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String, Object> requestMap = context.getExternalContext().getRequestMap();
        Integer errorCode = (Integer) requestMap.get("javax.servlet.error.status_code");
        if (errorCode != null) {
            String errorText = String.valueOf(errorCode);
            Object exception = requestMap.get("javax.servlet.error.exception");
            if (exception != null) {
                errorText += ": " + ((Exception) exception).getMessage();
            }
            return errorText;
        }
        return null;
    }
}

web/WEB-INF/templates/empty.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
>


</ui:composition>

web/WEB-INF/templates/footer.xhtml
<ui:composition
        xmlns:ui="http://java.sun.com/jsf/facelets"
>
    <!--

    <p:dataTable>
        <p:column headerText="1"/>
        <p:column headerText="2"/>
        <p:column headerText="3"/>
        <mysec:manager>
            <p:column headerText="4"/>
        </mysec:manager>
    </p:dataTable>
          -->

</ui:composition>

web/WEB-INF/templates/head.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>
            <ui:insert name="title">PrintAdmin - авторизация</ui:insert>
        </title>

        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

        <link rel="shortcut icon" type="image/x-icon" href="#{request.contextPath}/images/favicon.ico"/>

        <h:outputScript library="javax.faces" name="jsf.js" target="head"/>
        <h:outputScript library="omnifaces" name="fixviewstate.js" target="head"/>
        <h:outputScript library="script" name="script.js"/>
        <h:outputScript library="script" name="jquery.inputmask.js"/>

        <f:facet name="last">
            <h:outputStylesheet library="css" name="style.css"/>
        </f:facet>
    </h:head>
</ui:composition>

web/WEB-INF/templates/header.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:sec="http://iozee.ru/spring/security/tags"
        xmlns:pe="http://primefaces.org/ui/extensions">

    <h:form prependId="false" rendered="#{sec:isAuthorized()}">

        <p:growl id="growl" showDetail="true" showSummary="false" life="3800" autoUpdate="true"/>

        <p:dialog header="Внимание"
                  widgetVar="editMonitorAlert"
                  closeOnEscape="false"
                  width="420"
                  height="80"
                  resizable="false"
                  modal="true">
            Имеются несохраненные данные. Вы хотите закрыть страницу?
            <div class="formControlsBottom">
                <p:commandButton type="button"
                                 value="Да"
                                 styleClass="ui-confirmdialog-yes"
                                 icon="ui-icon-check"
                                 onclick="closeConfirm();"/>
                <p:commandButton type="button"
                                 value="Нет"
                                 styleClass="ui-confirmdialog-no"
                                 icon="ui-icon-close"
                                 onclick="PF('editMonitorAlert').hide();"/>
            </div>
        </p:dialog>

        <pe:tooltip global="true" myPosition="left center" atPosition="right center" showDelay="500"/>

        <p:idleMonitor timeout="#{userMB.idleTimeout}">

            <p:ajax event="idle"
                    listener="#{userMB.onIdle}"
                    process="@this"
                    partialSubmit="true"/>

            <p:ajax event="active"
                    listener="#{userMB.onActive}"
                    process="@this"
                    partialSubmit="true"/>

        </p:idleMonitor>
    </h:form>

</ui:composition>

web/WEB-INF/templates/masterTemplate.xhtml
<!DOCTYPE html [
        <!ENTITY nbsp "&#160;">
        ]>
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<o:importConstants type="com.iozee.printadmin.security.RolesEnum" var="Roles"/>

<ui:include src="head.xhtml"/>

<h:body>
    <ui:include src="header.xhtml"/>
    <ui:include src="menuOnepager.xhtml"/>
    <ui:insert name="content"/>
    <ui:include src="footer.xhtml"/>
</h:body>

</html>

web/WEB-INF/templates/menu.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:sec="http://iozee.ru/spring/security/tags">

    <h:form id="mainMenu" rendered="#{sec:isAuthorized()}">

        <!--<p:sticky target=":mainMenu:mainMenuBar"/>-->

        <p:menubar id="mainMenuBar" style="padding: 7px; margin: 0; z-index: 1" styleClass="noRoundCorners">

            <p:menuitem value="Главная"
                        url="/"
                        icon="fa fa-home"/>

            <p:menuitem value="Заказы"
                        url="/orders"
                        icon="fa fa-shopping-cart"
                        rendered="#{sec:isManager() or sec:isPrePress()}"/>

            <p:menuitem value="Клиенты"
                        url="/clients"
                        icon="fa fa-user"
                        rendered="#{sec:isManager()}"/>

            <p:menuitem value="Сотрудники"
                        url="/employees"
                        icon="fa fa-user-md"
                        rendered="#{sec:isManager() or sec:isPrePress()}"/>

            <p:menuitem value="Оборудование"
                        url="/machines"
                        icon="fa fa-print"
                        rendered="#{sec:isManager() or sec:isPrePress()}"/>

            <p:menuitem value="Настройки"
                        url="/settings"
                        icon="fa fa-gear"
                        rendered="#{sec:isSA()}"/>

            <f:facet name="options">
                <p:menuButton value="#{userMB.currentUser.name}"
                              id="userButton"
                              readonly="true"
                              icon="fa fa-user"
                              rendered="#{sec:isAuthorized()}">
                    <p:menuitem value="Выход"
                                url="logout"
                                icon="fa fa-power-off"/>
                </p:menuButton>
            </f:facet>

        </p:menubar>

    </h:form>

    <h:form>
        <h:panelGroup id="menu" layout="block">
            <h:form>
                <ul>
                    <li><p:commandLink value="orders" action="#{state.setPage('orders')}" update=":content"/></li>
                    <li><p:commandLink value="clients" action="#{state.setPage('clients')}" update=":content"/></li>
                </ul>
            </h:form>
        </h:panelGroup>
    </h:form>

</ui:composition>

web/WEB-INF/templates/menuOnepager.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:sec="http://iozee.ru/spring/security/tags">

    <h:form id="mainMenu" rendered="#{sec:isAuthorized()}">

        <!--<p:sticky target=":mainMenu:mainMenuBar"/>-->

        <p:menubar id="mainMenuBar" style="padding: 7px; margin: 0; z-index: 1" styleClass="noRoundCorners">

            <p:menuitem value="Заказы"
                        action="#{state.setPage('orders')}"
                        update=":mainContent"
                        icon="fa fa-shopping-cart"
                        rendered="#{sec:isManager() or sec:isPrePress()}"
                        ajax="true"
                        partialSubmit="true"
                        onstart="PF('mainContentBlock').block()"
                        oncomplete="PF('mainContentBlock').unblock()"/>

            <p:menuitem value="Клиенты"
                        action="#{state.setPage('clients')}"
                        update=":mainContent"
                        icon="fa fa-user"
                        rendered="#{sec:isManager()}"
                        ajax="true"
                        partialSubmit="true"
                        onstart="PF('mainContentBlock').block()"
                        oncomplete="PF('mainContentBlock').unblock()"/>

            <f:facet name="options">
                <p:menuButton value="#{userMB.currentUser.name}"
                              id="userButton"
                              readonly="true"
                              icon="fa fa-user"
                              rendered="#{sec:isAuthorized()}">
                    <p:menuitem value="Выход"
                                url="logout"
                                icon="fa fa-power-off"/>
                </p:menuButton>
            </f:facet>

        </p:menubar>


    </h:form>

</ui:composition>